---
- name: Install MySQL 8.0, Nginx, PHP-FPM 7.3, WP
  hosts: hostname
  #connection: local
  become: yes
  gather_facts: yes
  

  roles:
#FIRST WP INSTALL
#comment after all after first install
    - common
    - nginx
    - mysql
    - php-fpm
    - redis
    - wordpress
    
#INSTALL WP NETWORK
#comment out after first install
#    - network
